# Generated by Django 3.0.6 on 2020-06-02 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200531_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='bio',
            field=models.CharField(default='There was no bio-note provided for this author', max_length=2000),
        ),
    ]
